### ISSUE TITLE
HTML jquery component question

### ISSUE THREAD

**Issue by JohannesBuchner** [sgrubsmyon/morphr#1]
Hi Markus,

I also got interested into morphological analysis a while back. My project is here: https://github.com/JohannesBuchner/zwicky-morphological-analysis/ and uses only HTML+Javascript. I found it useful as  a thinking tool.

I was wondering how you used the jquery datatables plugin to allow navigation of allowed solutions (freezing the value of some columns and highlighting the remainders). I am interested in including such a navigation in my tool. 

I will also add a link to your project.

Cheers,
            Johannes

**Comment by sgrubsmyon** [comment]
Hi Johannes,



interesting that you use MA to solve puzzles like sudoku.



It seems your web based interface is not very user friendly. For example https://johannesbuchner.github.io/zwicky-morphological-analysis/#cats=Plan%3Afull_plan%20specific_plan%20routine_specific%20routine_general%20alertplan%3BTraining%3Aco-op%20specific%20base%2Bregular%20base%3BPersonnel%3A11%2B%208-10%205-7%20%3C4%3BEquipment%3Aspecial%20base%20subbase%3BLeadershipLevel%3A4%203%202%201%3BResponseChem%3A80%2510m%2080%2530m%2050%2515m%2050%2530m%20None30m%3BResponseInfo%3A%3C5min%20%3C30min%20%3E30min%3BResponsePeople%3Amany30min%20some15min%20some30min%20None30min&excl=full_plan%20specific%20*%20*%20*%20*%20*%20*%20%7C%20Plan%20not%20completely%20trained%20for%0Afull_plan%20base%2Bregular%20*%20*%20*%20*%20*%20*%20%7C%20Plan%20not%20completely%20trained%20for%0Afull_plan%20base%20*%20*%20*%20*%20*%20*%20%7C%20Plan%20not%20completely%20trained%20for%0Aspecific_plan%20base%2Bregular%20*%20*%20*%20*%20*%20*%20%7C%20Plan%20not%20completely%20trained%20for%0Aspecific_plan%20base%20*%20*%20*%20*%20*%20*%20%7C%20Plan%20not%20completely%20trained%20for%0Aroutine_specific%20base%20*%20*%20*%20*%20*%20*%20%7C%20Plan%20not%20completely%20trained%20for%0Aroutine_general%20co-op%20*%20*%20*%20*%20*%20*%20%7C%20Training%20without%20plan%0Aalertplan%20co-op%20*%20*%20*%20*%20*%20*%20%7C%20Training%20without%20plan%0Aalertplan%20specific%20*%20*%20*%20*%20*%20*%20%7C%20Training%20without%20plan%0Afull_plan%20*%20*%20subbase%20*%20*%20*%20*%20%7C%20Equipment%20worse%20than%20plan%0Aspecific_plan%20*%20*%20subbase%20*%20*%20*%20*%20%7C%20Equipment%20worse%20than%20plan%0Aroutine_specific%20*%20*%20subbase%20*%20*%20*%20*%20%7C%20Equipment%20worse%20than%20plan%0Aroutine_general%20*%20*%20special%20*%20*%20*%20*%20%7C%20Plan%20worse%20than%20equipment%0Aalertplan%20*%20*%20special%20*%20*%20*%20*%20%7C%20Plan%20worse%20than%20equipment%0Afull_plan%20*%20*%20*%203%20*%20*%20*%20%7C%20e%0Afull_plan%20*%20*%20*%202%20*%20*%20*%20%7C%20e%0Afull_plan%20*%20*%20*%201%20*%20*%20*%20%7C%20e%0Aspecific_plan%20*%20*%20*%202%20*%20*%20*%20%7C%20e%0Aspecific_plan%20*%20*%20*%201%20*%20*%20*%20%7C%20e%0Aroutine_specific%20*%20*%20*%201%20*%20*%20*%20%7C%20e%0Aroutine_general%20*%20*%20*%20*%2080%2510m%20*%20*%20%7C%20Generic%20response%20is%20slow%2Fineffective%0Aroutine_general%20*%20*%20*%20*%2080%2530m%20*%20*%20%7C%20Generic%20response%20is%20slow%2Fineffective%0Aroutine_general%20*%20*%20*%20*%2050%2515m%20*%20*%20%7C%20Generic%20response%20is%20slow%2Fineffective%0Aalertplan%20*%20*%20*%20*%2080%2510m%20*%20*%20%7C%20Alert-only%20is%20ineffective%0Aalertplan%20*%20*%20*%20*%2080%2530m%20*%20*%20%7C%20Alert-only%20is%20ineffective%0Aalertplan%20*%20*%20*%20*%2050%2515m%20*%20*%20%7C%20Alert-only%20is%20ineffective%0Aalertplan%20*%20*%20*%20*%2050%2530m%20*%20*%20%7C%20Alert-only%20is%20ineffective%0Aroutine_specific%20*%20*%20*%20*%20*%20%3C5min%20*%20%7C%20Generic%20response%20is%20slow%0Aroutine_general%20*%20*%20*%20*%20*%20%3C5min%20*%20%7C%20Generic%20response%20is%20slow%0Aalertplan%20*%20*%20*%20*%20*%20%3C5min%20*%20%7C%20Alert-only%20is%20ineffective%0A*%20base%2Bregular%20*%20special%20*%20*%20*%20*%20%7C%20cannot%20use%20special%20equipment%20with%20generic%20training%0A*%20base%20*%20special%20*%20*%20*%20*%20%7C%20cannot%20use%20special%20equipment%20with%20generic%20training%0A*%20base%2Bregular%20*%20*%20*%2080%2510m%20*%20*%20%7C%20generic%20training%20leads%20to%20slow%20response%0A*%20base%2Bregular%20*%20*%20*%2080%2530m%20*%20*%20%7C%20generic%20training%20leads%20to%20slow%20response%0A*%20base%2Bregular%20*%20*%20*%2050%2515m%20*%20*%20%7C%20generic%20training%20leads%20to%20slow%20response%0A*%20base%20*%20*%20*%2080%2510m%20*%20*%20%7C%20generic%20training%20leads%20to%20slow%20response%0A*%20base%20*%20*%20*%2080%2530m%20*%20*%20%7C%20generic%20training%20leads%20to%20slow%20response%0A*%20base%20*%20*%20*%2050%2515m%20*%20*%20%7C%20generic%20training%20leads%20to%20slow%20response%0A*%20*%2011%2B%20*%202%20*%20*%20*%20%7C%20h%0A*%20*%2011%2B%20*%201%20*%20*%20*%20%7C%20h%0A*%20*%208-10%20*%204%20*%20*%20*%20%7C%20number%20unavailable%0A*%20*%205-7%20*%204%20*%20*%20*%20%7C%20number%20unavailable%0A*%20*%205-7%20*%203%20*%20*%20*%20%7C%20number%20unavailable%0A*%20*%20%3C4%20*%204%20*%20*%20*%20%7C%20number%20unavailable%0A*%20*%20%3C4%20*%203%20*%20*%20*%20%7C%20number%20unavailable%0A*%20*%20%3C4%20*%202%20*%20*%20*%20%7C%20number%20unavailable%0A*%20*%20%3C4%20*%20*%2080%2510m%20*%20*%20%7C%20insufficient%20manpower%0A*%20*%20%3C4%20*%20*%2080%2530m%20*%20*%20%7C%20insufficient%20manpower%0A*%20*%20%3C4%20*%20*%2050%2515m%20*%20*%20%7C%20insufficient%20manpower%0A*%20*%20%3C4%20*%20*%2050%2530m%20*%20*%20%7C%20insufficient%20manpower%0A*%20*%20*%20base%20*%2080%2510m%20*%20*%20%7C%20generic%20equipment%20does%20not%20allow%20fast%20response%0A*%20*%20*%20base%20*%2080%2530m%20*%20*%20%7C%20generic%20equipment%20does%20not%20allow%20complete%20response%0A*%20*%20*%20subbase%20*%2080%2510m%20*%20*%20%7C%20poor%20equipment%20does%20not%20allow%20complete%20response%0A*%20*%20*%20subbase%20*%2080%2530m%20*%20*%20%7C%20poor%20equipment%20does%20not%20allow%20complete%20response%0A*%20*%20*%20subbase%20*%2050%2515m%20*%20*%20%7C%20poor%20equipment%20does%20not%20allow%20fast%20response%0A is hard to understand compared to the MA/CARMA visualization shown in the video https://www.youtube.com/watch?v=x4zAniSP0FY.



My intent was rather to more or less create a copy of the CARMA features, especially the interactive highlighting of the possible value combinations.



I didn't program this in JavaScript or even JQuery, but used the R framework Shiny. Since I am using R Shiny a lot in my work, it was easier for me to both develop it and integrate it into other projects. But it's a lot less accessible to other folks than a pure JS solution.



Here you can learn more about the R Shiny wrapper around the JQuery datatables plugin: https://rstudio.github.io/DT/ Here is more about the interactive features that allow to react to user clicks on the table: https://rstudio.github.io/DT/shiny.html#interaction-with-shiny. Observing the variable input$tableId_cells_selected in Shiny's reactive framework, one can react to it. The R Shiny server calculates the result and sends it back to the browser via an R-Javascript interface provided by Shiny.



In principle, one could do the same thing in pure JS/JQuery relatively easily. One just needs to listen for cell selection events like this: https://datatables.net/reference/event/select with the on() API: https://datatables.net/reference/api/on().



Cheers,

Markus

**Comment by JohannesBuchner** [comment]
Thank you, I will look into the datatables. I am still looking for ways to improve the web tool, and patches are welcome. 

I suppose there are different applications for MA, I use it mostly to build systematic arguments (so I want a list of solutions or why options can be excluded), or generally to explore complex solution spaces. The CARMA software (which I have never used) seems more tailored to business solutions.
